### ISSUE TITLE
Cannot Run Code

### ISSUE THREAD

**Issue by MankowitzProjects** [deeplearning4j/gym-java-client#6]
Hi,
I tried cloning the source as well as downloading the jar from Maven repository.

When I clone the source, there are many dependencies missing. Are you able to send me the related jars as I am concerned that the jars I have downloaded are problematic. For example, when I run the unit test on the ClientTest.java file, I get the exception:

java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexNumber
    at org.deeplearning4j.rl4j.space.GymObservationSpace.<init>(GymObservationSpace.java:38)
    at org.deeplearning4j.gym.ClientFactory.fetchObservationSpace(ClientFactory.java:72)
    at org.deeplearning4j.gym.ClientFactory.build(ClientFactory.java:34)
    at org.deeplearning4j.gym.test.ClientTest.completeClientTest(ClientTest.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:316)
    at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
    at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:300)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:288)
    at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:147)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)
    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)
    at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
    at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
    at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexNumber
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:190)
    at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
    at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more

When I download the jar file from the maven repository, I get the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
    at com.mashape.unirest.request.HttpRequestWithBody.body(HttpRequestWithBody.java:146)
    at com.mashape.unirest.request.HttpRequestWithBody.body(HttpRequestWithBody.java:174)
    at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:23)
    at org.deeplearning4j.gym.ClientFactory.build(ClientFactory.java:24)
    at com.openaigym.Test.main(Test.java:27)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more

My source code is below for the main class is below. Any help would be much appreciated.

package com.openaigym;

import java.io.IOException;

import org.deeplearning4j.gym.Client;
import org.deeplearning4j.gym.ClientFactory;
import org.deeplearning4j.gym.ClientUtils;
import org.deeplearning4j.gym.StepReply;
import org.deeplearning4j.rl4j.space.Box;
import org.deeplearning4j.rl4j.space.DiscreteSpace;

public class Test {

    public static void main(String[] args) throws IOException {

        String url = "http://127.0.0.1:5000";
        String env = "CartPole-v0";
        String instanceID = "e15739cf";
        String testDir = "/tmp/testDir";
        boolean render = true;
        String renderStr = render ? "True" : "False";
       
        Client<Box, Integer, DiscreteSpace> client = ClientFactory.build(url, env, render);
        client.monitorStart(testDir, true, false);

        int episodeCount = 1;
        int maxSteps = 200;
        int reward = 0;

        for (int i = 0; i < episodeCount; i++) {
            client.reset();

            for (int j = 0; j < maxSteps; j++) {

                Integer action = client.getActionSpace().randomAction();
                StepReply<Box> step = client.step(action);
                reward += step.getReward();

                if (step.isDone()) {
                    // System.out.println("break");
                    break;
                }
            }

        }

        client.monitorClose();
        client.upload(testDir, "YOUR_OPENAI_GYM_API_KEY");
    }

}

Thanks,
Daniel

**Comment by agibsonccc** [comment]
Can you post a github project I can look at?

**Comment by MankowitzProjects** [comment]
Sure. I have uploaded it to git. I am running the project in Eclipse.
The repo address is:
https://github.com/MankowitzProjects/openai-gym-test.git

I have included the libs that I have tried using to get the project to run in a libs folder.

**Comment by agibsonccc** [comment]
thanks!

**Comment by MankowitzProjects** [comment]
I am also running Ubuntu 14.04 if that helps

**Comment by MankowitzProjects** [comment]
Hi,

Did you manage to find the issue?

Thanks

**Comment by agibsonccc** [comment]
Haven't looked in to it yet. I run a company.Dl4j is a large project with a large community and a lot going on. I do not provide SLAs to people filing issues on github. I will let you know when I get to it. Thanks!

**Comment by MankowitzProjects** [comment]
No problem. Quick question:
Is it crucial to use the 0.7.3 SNAPSHOT? Should it be problematic if I use 0.7.2?

**Comment by agibsonccc** [comment]
It shouldn't be.  We haven't been doing much to this besides maintenance. I
planned on getting to this this weekend after my current backlog.

**Comment by MankowitzProjects** [comment]
Thanks, I appreciate your help.

**Comment by agibsonccc** [comment]
K so looking at this..first of all, learn a build system. There is a reason maven and exists throughout all of our examples.

If you are normally from the python world, imagine not using pip and instead downloading all the python files by hand 1 by 1. That is basically what you are doing here. If you are not familiar with a java based build system, now might be a good time to learn one. You should be able to run our examples right out of the box: https://github.com/deeplearning4j/dl4j-examples/tree/master/rl4j-examples

Your ide knows how to use maven, take 5 minutes and learn the basics.
